[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "carve"
version = "0.1.0"
requires-python = ">=3.12,<3.13"
dependencies = [
  "numpy>=2.0,<2.1",
  "scipy>=1.16,<1.17",
  "scikit-learn>=1.7.2,<1.8",
  "pandas>=2.2,<2.3",
  "joblib>=1.5,<1.6",
  "tqdm>=4.67,<5",
  "numba>=0.60,<0.61",
  "llvmlite>=0.43,<0.44",
  "umap-learn>=0.5.6",
  "pynndescent>=0.5.10,<0.6",
  "jupyterlab>=4.2,<5",
  "ipykernel>=6.29,<7",
  "matplotlib>=3.9.4",
  "ipywidgets>=8.1.7",
  "plotly>=6.3.0",
  "rpy2>=3.6.3",
  "pyreadr>=0.5.3",
  "scanpy>=1.11.4",
  "scikit-misc>=0.5.1",
  "anywidget>=0.9.18",
  "igraph>=1.0.0",
  "leidenalg>=0.11.0",
  "pyteomics>=4.7.5",
  "lxml>=6.0.2",
  "scvi>=0.6.8",
]

[project.optional-dependencies]
dev = [
  "ruff",
  "pytest",
]

[tool.setuptools.packages.find]
where = ["src"]
